###############################
# Swagger
###############################

fr.insee.rmes.magmaFusion.force.ssl=false
springdoc.swagger-ui.path= /
fr.insee.rmes.security.enabled=true
springdoc.swagger-ui.enabled=true
spring.profile.active=dev
fr.insee.rmes.magmaFusion.bauhaus.url=

###############################
# Bdd de gestion
###############################
fr.insee.rmes.magmaFusion.gestion.rdfServer =
fr.insee.rmes.magmaFusion.gestion.repository = gestion
fr.insee.rmes.role.administrateur=
fr.insee.rmes.role.gestionnaire.dataset=Gestionnaire_jeu_donnees_RMESGNCS

##SWAGGER
springdoc.swagger-ui.oauth.clientId=
fr.insee.rmes.auth.url= 
fr.insee.rmes.springdoc.issuer-url-authorization=
fr.insee.rmes.springdoc.issuer-url-refresh=
fr.insee.rmes.springdoc.issuer-url-token=
fr.insee.rmes.springdoc.issuer-description=Keycloak
fr.insee.rmes.springdoc.contact-name=DR59-SNDIL
fr.insee.rmes.springdoc.contact-email=un-email-fonctionnel@insee.fr
fr.insee.rmes.springdoc.contact-url=https://www.insee.fr/fr/accueil
fr.insee.rmes.security.whitelist-matchers=/swagger-ui/index.html,/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html,/actuator/**,/error,/,/swagger-ui-magma.html

#Configuration du jeton JWT
# Security configuration
fr.insee.rmes.security.token.oidc-claim-role=realm_access
fr.insee.rmes.security.token.oidc-claim-username=preferred_username
fr.insee.rmes.security.token.oidc-roles-in-claim-role=roles
fr.insee.rmes.security.token.email=email
spring.security.oauth2.resourceserver.jwt.issuer-uri=


fr.insee.rmes.magmaFusion.lg1 = fr
fr.insee.rmes.magmaFusion.lg2 = en
fr.insee.rmes.magmaFusion.perPage = 5

fr.insee.rmes.magmaFusion.baseGraph = http://rdf.insee.fr/graphes/
fr.insee.rmes.magmaFusion.gestion.baseURI = http://bauhaus/

###############################
#CONCEPTS AND COLLECTIONS
###############################
fr.insee.rmes.magmaFusion.concepts.scheme = concepts/definitions/scheme
fr.insee.rmes.magmaFusion.concepts.graph = concepts/definitions
fr.insee.rmes.magmaFusion.concepts.baseURI = concepts
fr.insee.rmes.magmaFusion.collections.baseURI = concepts/definitions


fr.insee.rmes.magmaFusion.concepts.defaultContributor = DG75-L201
fr.insee.rmes.magmaFusion.concepts.defaultMailSender =
fr.insee.rmes.magmaFusion.concepts.maxLengthScopeNote = 350


###############################
#STRUCTURES
###############################
fr.insee.rmes.magmaFusion.structures.graph = structures
fr.insee.rmes.magmaFusion.structures.baseURI = structuresDeDonnees/structure
fr.insee.rmes.magmaFusion.structures.components.graph = composants
fr.insee.rmes.magmaFusion.structures.components.baseURI = structuresDeDonnees/composants/


###############################
#CODELIST
###############################
fr.insee.rmes.magmaFusion.codeLists.graph = codes
fr.insee.rmes.magmaFusion.codeLists.baseURI= codes

###############################
#OPERATION
###############################
fr.insee.rmes.magmaFusion.operations.graph = operations
fr.insee.rmes.magmaFusion.operations.baseURI = operations/operation
fr.insee.rmes.magmaFusion.operations.families.baseURI = operations/famille
fr.insee.rmes.magmaFusion.operations.series.baseURI = operations/serie

#ORGANISATIONS
fr.insee.rmes.magmaFusion.organisations.graph = organisations

#ADMS
fr.insee.rmes.magmaFusion.adms.graph = adms

#OPERATIONS - SIMS
fr.insee.rmes.magmaFusion.documentations.baseURI = qualite/rapport
fr.insee.rmes.magmaFusion.documentations.graph = qualite/
fr.insee.rmes.magmaFusion.documentation.geographie.baseURI=qualite/territoire

#DATASETS
fr.insee.rmes.magmaFusion.datasets.baseURI= datasets/
fr.insee.rmes.magmaFusion.datasets.graph= catalogue

#OPERATIONS - INDICATEURS
fr.insee.rmes.magmaFusion.products.graph = produits
fr.insee.rmes.magmaFusion.products.baseURI = produits/indicateur

#OPERATIONS - DOCUMENTS
fr.insee.rmes.magmaFusion.documents.graph = qualite/documents
fr.insee.rmes.magmaFusion.documents.baseURI = documents/document
fr.insee.rmes.magmaFusion.links.baseURI = documents/page

#ONTOLOGIES
fr.insee.rmes.magmaFusion.ontologies.baseURI = ontologies/insee/base

###############################
# SPARQL (diffusion)
###############################
fr.insee.rmes.magmaFusion.api.sparqlEndpoint=

###############################
# FreeMarker
###############################
fr.insee.rmes.magmaFusion.api.freemarker.locale-language=fr

###############################
# Jackson
###############################
spring.jackson.mapper.sort-properties-alphabetically=false

###############################
# Logs
###############################
properties.logger.prefix-for-properties=fr,debug,trace,info,logging,spring,server,management,springdoc,properties

###############################
# Géographie
###############################
fr.insee.rmes.magmaFusion.api.geographie.types-autorises=Commune,CommuneAssociee,CommuneDeleguee,Canton,CantonOuVille,Arrondissement,ArrondissementMunicipal,Departement,Pays,Region,Intercommunalite,District,AireDAttractionDesVilles2020,BassinDeVie2022,CollectiviteDOutreMer,CirconscriptionTerritoriale,Iris,QuartierPrioritaireDeLaPolitiqueDeLaVille2024,ZoneDEmploi2020,UniteUrbaine2020
